global using JobPortal.Domain.Entities;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using JobPortal.Domain.Common;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using JobPortal.Infrastructure.Context;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;